# Generated by Django 4.2.4 on 2023-11-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tournamentfixture_team_won_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentfixture',
            name='match_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
